Feature/1
EppyTrLove/Auth pull request #8
Opened 2024-07-30 12:43 UTC by EppyTrLove

User model created

2024-07-30 16:34 UTC, sstcvetkov requested changes

2024-07-30 16:34 UTC, sstcvetkov commented on NikEp.Auth.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Test", "Test", "{2EC1E9AC-A9C1-4569-982A-51E04CAE3034}"
Давай сделаем с маленькой буквы, аналогично `src`

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Program.cs
Этот файл можно удалить, т.к. эта сборка не исполняемая

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        [Required(ErrorMessage = "Email required")]
Конкрентно эти атрибуты валидации обычно используют в рамках asp пайплайна, а это число доменная сборка, давай их уберем от сюда

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +            PhoneNumber phoneNumber, Guid id, DateTime createdAt)
Конструктор должен принимать email тоже как VO. 
id и createdAt давай будем не принимать, а задавать сами, внутри конструктора User

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +    internal class User
Доменной сборкой будут пользоваться остальные сборки, по этому тут надо `public`

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        public string ConfirmPassword { get; set; }
Это чисто ui-ное дело - проверять что пользователь отдает себе отчет о том, какой именно пароль вводит. Бэк работает просто с паролем.

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        [StringLength(10, MinimumLength = 3, ErrorMessage = "Wrong password. Please, try again.")]
Подобные проверки надо перенести в конструктор, цель в том чтобы не дать создать экземпляр пользователя в некорректном состоянии

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        [DisplayName("Password")]
Опять же, доменная модель не должна знать как ее отображают, это дело условного UI

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        public DateTime LoggedinAt { get; set; }
Давай сделаем это поле nullable, ведь пользователь может и не залогиниться

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/ValueObjects/Age.cs
> +        public string UserAge { get; } // TODO:добавить валидацию
В целом я бы назвал просто age, т.к. возраст может быть не только у пользователя.

Кажется что иметь такое поле это не серьезно, возраст меняется, его лучше высчитывать на ходу, а хранить вместо этого просто дату рождения.

2024-07-30 16:34 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/ValueObjects/Name.cs
> +        //}
Закомментированных кусков кода в рабочем коде не должно быть

2024-07-30 16:34 UTC, sstcvetkov commented on test/NikEp.Auth.Domain.UnitTests/ValueObjects/NameTests.cs
> +        public void Create_(string? value, bool expectedSucsess)
`CreateTest`

2024-07-30 16:34 UTC, sstcvetkov commented on test/NikEp.Auth.Domain.UnitTests/ValueObjects/NameTests.cs
> +        [TestCase(null, false)]
Это всего один негативный кес, надо бы добавить еще. А также минимум один позитивный кес - когда данные валидны для создания инстанса

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        public Email Email { get; set; }
Давай закроем все сеттеры. Наша цель недопустить неконсистеноного состояния объекта

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        public string ConfirmPassword { get; set; }
Это лишнее

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +            if (Enumerable.Range(3, 10).Contains(password.Length))
Виглядит очень странно. Во первых, здесь создается ненужная коллекция, во вторых мы перебираем все элесенты и затем сравниваем, в трерьих это читается сложнее чем `password.Length >= 3 && password.Length <= 10`. Кроме того можно воспользоваться паттер матчингом с написатьак:
`passwordюLength is >= 3 and <= 10`

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        private Id Id { get; set; }
В будующем эту модель будут многократно читать потенциальные коллеги, для удобства лучше группировать поля

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +            else throw new ArgumentException("Wrong password. Please, try again.");
В таких случаях(валидация\проверки), вместо 2х веток развития лучше делать одну. 
Читатель по умолчанию предполагает что метод делает свою задачу(позитивный сценарий).
А здесь ты заставляешь его провалиться в if ради ничего

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/ValueObjects/Email.cs
> +            Regex regex = new Regex(@"^[\w!#$%&'*+\-/=?\^_`{|}~]+(\.[\w!#$%&'*+\-/=?\^_`{|}~]+)*" + "@"
Давай вынесем регулярное выражение в  константу или приватное поле

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/ValueObjects/Email.cs
> +            if (String.IsNullOrEmpty(value)) return (false, "You entered an empty Email", null);
Кажется `entered ` здесь несовсем правильно. Если пользователь попадет сюда не со страницы ввода а как то через  api, то это уже будет не ввод. Давай просто скажем что иейл пустой

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/ValueObjects/Email.cs
> +        private static string _value { get; set; }
статик?)

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/ValueObjects/Id.cs
> +    public record class Id
Здесь `record class` , далее просто `record` что одно и то же. Давай делать единообразно

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/ValueObjects/PhoneNumber.cs
> +            else throw new ArgumentException();
Снова странноветвление

2024-08-02 08:28 UTC, sstcvetkov commented on test/NikEp.Auth.Domain.UnitTests/NikEp.Auth.Domain.UnitTests.csproj
> +    <TargetFramework>net6.0</TargetFramework>
Может перейдем на 8й сразу?)

2024-08-02 08:28 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/NikEp.Auth.Domain.csproj
>      <TargetFramework>net6.0</TargetFramework>
Давй делать на 8м

2024-08-02 09:26 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/Entities/User.cs
> +        private Id Id { get; set; }
Сгруппировал, посмотри

2024-08-02 09:27 UTC, sstcvetkov commented
Комментарий

2024-08-02 09:47 UTC, sstcvetkov commented on src/NikEp.Auth.Domain/ValueObjects/Name.cs
> +    public record Name
Добавь поддержку латиницы

2024-08-12 16:01 UTC, EppyTrLove commented on src/NikEp.Auth.Domain/ValueObjects/PhoneNumber.cs
> +            else throw new ArgumentException();
Есть вопрос. Может ли нам в number в принципе прийти null? стоит ли делать на это проверку?

2024-09-27 10:32 UTC, merged